//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ca21.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Ca21.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class Ca21Parser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ExternKeyword=1, ExportKeyword=2, FuncKeyword=3, LetKeyword=4, MutKeyword=5, 
		Int32Keyword=6, BoolKeyword=7, StrKeyword=8, TrueKeyword=9, FalseKeyword=10, 
		WhileKeyword=11, ReturnKeyword=12, String=13, Integer=14, Identifier=15, 
		Comma=16, LeftParenthesis=17, RightParenthesis=18, LeftBrace=19, RightBrace=20, 
		Semicolon=21, Star=22, Slash=23, Percentage=24, Plus=25, Minus=26, LessThan=27, 
		LessThanOrEqual=28, GreaterThan=29, GreaterThanOrEqual=30, Equal=31, Whitespace=32;
	public const int
		RULE_compilationUnit = 0, RULE_functionDefinition = 1, RULE_functionSignature = 2, 
		RULE_parameterList = 3, RULE_parameterDefinition = 4, RULE_typeReference = 5, 
		RULE_typeKeyword = 6, RULE_block = 7, RULE_statement = 8, RULE_localDeclaration = 9, 
		RULE_expressionOrBlock = 10, RULE_expression = 11, RULE_argumentList = 12, 
		RULE_literal = 13;
	public static readonly string[] ruleNames = {
		"compilationUnit", "functionDefinition", "functionSignature", "parameterList", 
		"parameterDefinition", "typeReference", "typeKeyword", "block", "statement", 
		"localDeclaration", "expressionOrBlock", "expression", "argumentList", 
		"literal"
	};

	private static readonly string[] _LiteralNames = {
		null, "'extern'", "'export'", "'func'", "'let'", "'mut'", "'int32'", "'bool'", 
		"'str'", "'true'", "'false'", "'while'", "'return'", null, null, null, 
		"','", "'('", "')'", "'{'", "'}'", "';'", "'*'", "'/'", "'%'", "'+'", 
		"'-'", "'<'", "'<='", "'>'", "'>='", "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ExternKeyword", "ExportKeyword", "FuncKeyword", "LetKeyword", "MutKeyword", 
		"Int32Keyword", "BoolKeyword", "StrKeyword", "TrueKeyword", "FalseKeyword", 
		"WhileKeyword", "ReturnKeyword", "String", "Integer", "Identifier", "Comma", 
		"LeftParenthesis", "RightParenthesis", "LeftBrace", "RightBrace", "Semicolon", 
		"Star", "Slash", "Percentage", "Plus", "Minus", "LessThan", "LessThanOrEqual", 
		"GreaterThan", "GreaterThanOrEqual", "Equal", "Whitespace"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Ca21.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static Ca21Parser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public Ca21Parser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public Ca21Parser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class CompilationUnitContext : ParserRuleContext {
		public FunctionDefinitionContext _functionDefinition;
		public IList<FunctionDefinitionContext> _Functions = new List<FunctionDefinitionContext>();
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(Ca21Parser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionDefinitionContext[] functionDefinition() {
			return GetRuleContexts<FunctionDefinitionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionDefinitionContext functionDefinition(int i) {
			return GetRuleContext<FunctionDefinitionContext>(i);
		}
		public CompilationUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compilationUnit; } }
	}

	[RuleVersion(0)]
	public CompilationUnitContext compilationUnit() {
		CompilationUnitContext _localctx = new CompilationUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compilationUnit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 29;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 28;
				_localctx._functionDefinition = functionDefinition();
				_localctx._Functions.Add(_localctx._functionDefinition);
				}
				}
				State = 31;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 14L) != 0) );
			State = 33;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDefinitionContext : ParserRuleContext {
		public FunctionDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDefinition; } }
	 
		public FunctionDefinitionContext() { }
		public virtual void CopyFrom(FunctionDefinitionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TopLevelFunctionDefinitionContext : FunctionDefinitionContext {
		public IToken ExportModifier;
		public FunctionSignatureContext Signature;
		public BlockContext Body;
		[System.Diagnostics.DebuggerNonUserCode] public FunctionSignatureContext functionSignature() {
			return GetRuleContext<FunctionSignatureContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ExportKeyword() { return GetToken(Ca21Parser.ExportKeyword, 0); }
		public TopLevelFunctionDefinitionContext(FunctionDefinitionContext context) { CopyFrom(context); }
	}
	public partial class ExternFunctionDefinitionContext : FunctionDefinitionContext {
		public IToken ExternName;
		public FunctionSignatureContext Signature;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ExternKeyword() { return GetToken(Ca21Parser.ExternKeyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParenthesis() { return GetToken(Ca21Parser.LeftParenthesis, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParenthesis() { return GetToken(Ca21Parser.RightParenthesis, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Semicolon() { return GetToken(Ca21Parser.Semicolon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode String() { return GetToken(Ca21Parser.String, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionSignatureContext functionSignature() {
			return GetRuleContext<FunctionSignatureContext>(0);
		}
		public ExternFunctionDefinitionContext(FunctionDefinitionContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public FunctionDefinitionContext functionDefinition() {
		FunctionDefinitionContext _localctx = new FunctionDefinitionContext(Context, State);
		EnterRule(_localctx, 2, RULE_functionDefinition);
		int _la;
		try {
			State = 48;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ExportKeyword:
			case FuncKeyword:
				_localctx = new TopLevelFunctionDefinitionContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 36;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ExportKeyword) {
					{
					State = 35;
					((TopLevelFunctionDefinitionContext)_localctx).ExportModifier = Match(ExportKeyword);
					}
				}

				State = 38;
				((TopLevelFunctionDefinitionContext)_localctx).Signature = functionSignature();
				State = 39;
				((TopLevelFunctionDefinitionContext)_localctx).Body = block();
				}
				break;
			case ExternKeyword:
				_localctx = new ExternFunctionDefinitionContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 41;
				Match(ExternKeyword);
				State = 42;
				Match(LeftParenthesis);
				State = 43;
				((ExternFunctionDefinitionContext)_localctx).ExternName = Match(String);
				State = 44;
				Match(RightParenthesis);
				State = 45;
				((ExternFunctionDefinitionContext)_localctx).Signature = functionSignature();
				State = 46;
				Match(Semicolon);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionSignatureContext : ParserRuleContext {
		public IToken Name;
		public ParameterListContext ParameterList;
		public TypeReferenceContext ReturnType;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FuncKeyword() { return GetToken(Ca21Parser.FuncKeyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParenthesis() { return GetToken(Ca21Parser.LeftParenthesis, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParenthesis() { return GetToken(Ca21Parser.RightParenthesis, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(Ca21Parser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParameterListContext parameterList() {
			return GetRuleContext<ParameterListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeReferenceContext typeReference() {
			return GetRuleContext<TypeReferenceContext>(0);
		}
		public FunctionSignatureContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionSignature; } }
	}

	[RuleVersion(0)]
	public FunctionSignatureContext functionSignature() {
		FunctionSignatureContext _localctx = new FunctionSignatureContext(Context, State);
		EnterRule(_localctx, 4, RULE_functionSignature);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			Match(FuncKeyword);
			State = 51;
			_localctx.Name = Match(Identifier);
			State = 52;
			Match(LeftParenthesis);
			State = 54;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MutKeyword || _la==Identifier) {
				{
				State = 53;
				_localctx.ParameterList = parameterList();
				}
			}

			State = 56;
			Match(RightParenthesis);
			State = 58;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 448L) != 0)) {
				{
				State = 57;
				_localctx.ReturnType = typeReference();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterListContext : ParserRuleContext {
		public ParameterDefinitionContext _parameterDefinition;
		public IList<ParameterDefinitionContext> _Parameters = new List<ParameterDefinitionContext>();
		[System.Diagnostics.DebuggerNonUserCode] public ParameterDefinitionContext[] parameterDefinition() {
			return GetRuleContexts<ParameterDefinitionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ParameterDefinitionContext parameterDefinition(int i) {
			return GetRuleContext<ParameterDefinitionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(Ca21Parser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(Ca21Parser.Comma, i);
		}
		public ParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterList; } }
	}

	[RuleVersion(0)]
	public ParameterListContext parameterList() {
		ParameterListContext _localctx = new ParameterListContext(Context, State);
		EnterRule(_localctx, 6, RULE_parameterList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			_localctx._parameterDefinition = parameterDefinition();
			_localctx._Parameters.Add(_localctx._parameterDefinition);
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 61;
				Match(Comma);
				State = 62;
				_localctx._parameterDefinition = parameterDefinition();
				_localctx._Parameters.Add(_localctx._parameterDefinition);
				}
				}
				State = 67;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterDefinitionContext : ParserRuleContext {
		public IToken MutModifier;
		public IToken Name;
		public TypeReferenceContext Type;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(Ca21Parser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeReferenceContext typeReference() {
			return GetRuleContext<TypeReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MutKeyword() { return GetToken(Ca21Parser.MutKeyword, 0); }
		public ParameterDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterDefinition; } }
	}

	[RuleVersion(0)]
	public ParameterDefinitionContext parameterDefinition() {
		ParameterDefinitionContext _localctx = new ParameterDefinitionContext(Context, State);
		EnterRule(_localctx, 8, RULE_parameterDefinition);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MutKeyword) {
				{
				State = 68;
				_localctx.MutModifier = Match(MutKeyword);
				}
			}

			State = 71;
			_localctx.Name = Match(Identifier);
			State = 72;
			_localctx.Type = typeReference();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeReferenceContext : ParserRuleContext {
		public TypeReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeReference; } }
	 
		public TypeReferenceContext() { }
		public virtual void CopyFrom(TypeReferenceContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NativeTypeReferenceContext : TypeReferenceContext {
		public TypeKeywordContext NativeType;
		[System.Diagnostics.DebuggerNonUserCode] public TypeKeywordContext typeKeyword() {
			return GetRuleContext<TypeKeywordContext>(0);
		}
		public NativeTypeReferenceContext(TypeReferenceContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public TypeReferenceContext typeReference() {
		TypeReferenceContext _localctx = new TypeReferenceContext(Context, State);
		EnterRule(_localctx, 10, RULE_typeReference);
		try {
			_localctx = new NativeTypeReferenceContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			((NativeTypeReferenceContext)_localctx).NativeType = typeKeyword();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeKeywordContext : ParserRuleContext {
		public IToken Keyword;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Int32Keyword() { return GetToken(Ca21Parser.Int32Keyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StrKeyword() { return GetToken(Ca21Parser.StrKeyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BoolKeyword() { return GetToken(Ca21Parser.BoolKeyword, 0); }
		public TypeKeywordContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeKeyword; } }
	}

	[RuleVersion(0)]
	public TypeKeywordContext typeKeyword() {
		TypeKeywordContext _localctx = new TypeKeywordContext(Context, State);
		EnterRule(_localctx, 12, RULE_typeKeyword);
		try {
			State = 79;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Int32Keyword:
				EnterOuterAlt(_localctx, 1);
				{
				State = 76;
				_localctx.Keyword = Match(Int32Keyword);
				}
				break;
			case StrKeyword:
				EnterOuterAlt(_localctx, 2);
				{
				State = 77;
				_localctx.Keyword = Match(StrKeyword);
				}
				break;
			case BoolKeyword:
				EnterOuterAlt(_localctx, 3);
				{
				State = 78;
				_localctx.Keyword = Match(BoolKeyword);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public StatementContext _statement;
		public IList<StatementContext> _Statements = new List<StatementContext>();
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftBrace() { return GetToken(Ca21Parser.LeftBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightBrace() { return GetToken(Ca21Parser.RightBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 14, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			Match(LeftBrace);
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 589328L) != 0)) {
				{
				{
				State = 82;
				_localctx._statement = statement();
				_localctx._Statements.Add(_localctx._statement);
				}
				}
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 88;
			Match(RightBrace);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	 
		public StatementContext() { }
		public virtual void CopyFrom(StatementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ExpressionStatementContext : StatementContext {
		public ExpressionContext Expression;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Semicolon() { return GetToken(Ca21Parser.Semicolon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ExpressionStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class ReturnStatementContext : StatementContext {
		public ExpressionOrBlockContext Value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ReturnKeyword() { return GetToken(Ca21Parser.ReturnKeyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Semicolon() { return GetToken(Ca21Parser.Semicolon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionOrBlockContext expressionOrBlock() {
			return GetRuleContext<ExpressionOrBlockContext>(0);
		}
		public ReturnStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class BlockStatementContext : StatementContext {
		public BlockContext Block;
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public BlockStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class WhileStatementContext : StatementContext {
		public ExpressionContext Condition;
		public BlockContext Body;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WhileKeyword() { return GetToken(Ca21Parser.WhileKeyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public WhileStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class LocalDeclarationStatementContext : StatementContext {
		public LocalDeclarationContext Declaration;
		[System.Diagnostics.DebuggerNonUserCode] public LocalDeclarationContext localDeclaration() {
			return GetRuleContext<LocalDeclarationContext>(0);
		}
		public LocalDeclarationStatementContext(StatementContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 16, RULE_statement);
		try {
			State = 103;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LetKeyword:
				_localctx = new LocalDeclarationStatementContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 90;
				((LocalDeclarationStatementContext)_localctx).Declaration = localDeclaration();
				}
				break;
			case WhileKeyword:
				_localctx = new WhileStatementContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 91;
				Match(WhileKeyword);
				State = 92;
				((WhileStatementContext)_localctx).Condition = expression(0);
				State = 93;
				((WhileStatementContext)_localctx).Body = block();
				}
				break;
			case ReturnKeyword:
				_localctx = new ReturnStatementContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 95;
				Match(ReturnKeyword);
				State = 96;
				((ReturnStatementContext)_localctx).Value = expressionOrBlock();
				State = 97;
				Match(Semicolon);
				}
				break;
			case LeftBrace:
				_localctx = new BlockStatementContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 99;
				((BlockStatementContext)_localctx).Block = block();
				}
				break;
			case TrueKeyword:
			case FalseKeyword:
			case String:
			case Integer:
			case Identifier:
				_localctx = new ExpressionStatementContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 100;
				((ExpressionStatementContext)_localctx).Expression = expression(0);
				State = 101;
				Match(Semicolon);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LocalDeclarationContext : ParserRuleContext {
		public IToken MutModifier;
		public IToken Name;
		public ExpressionOrBlockContext Value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LetKeyword() { return GetToken(Ca21Parser.LetKeyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Equal() { return GetToken(Ca21Parser.Equal, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Semicolon() { return GetToken(Ca21Parser.Semicolon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(Ca21Parser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionOrBlockContext expressionOrBlock() {
			return GetRuleContext<ExpressionOrBlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MutKeyword() { return GetToken(Ca21Parser.MutKeyword, 0); }
		public LocalDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_localDeclaration; } }
	}

	[RuleVersion(0)]
	public LocalDeclarationContext localDeclaration() {
		LocalDeclarationContext _localctx = new LocalDeclarationContext(Context, State);
		EnterRule(_localctx, 18, RULE_localDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			Match(LetKeyword);
			State = 107;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MutKeyword) {
				{
				State = 106;
				_localctx.MutModifier = Match(MutKeyword);
				}
			}

			State = 109;
			_localctx.Name = Match(Identifier);
			State = 110;
			Match(Equal);
			State = 111;
			_localctx.Value = expressionOrBlock();
			State = 112;
			Match(Semicolon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionOrBlockContext : ParserRuleContext {
		public ExpressionOrBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionOrBlock; } }
	 
		public ExpressionOrBlockContext() { }
		public virtual void CopyFrom(ExpressionOrBlockContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NonBlockExpressionContext : ExpressionOrBlockContext {
		public ExpressionContext Expression;
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public NonBlockExpressionContext(ExpressionOrBlockContext context) { CopyFrom(context); }
	}
	public partial class BlockExpressionContext : ExpressionOrBlockContext {
		public StatementContext _statement;
		public IList<StatementContext> _Statements = new List<StatementContext>();
		public ExpressionContext Tail;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftBrace() { return GetToken(Ca21Parser.LeftBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightBrace() { return GetToken(Ca21Parser.RightBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public BlockExpressionContext(ExpressionOrBlockContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ExpressionOrBlockContext expressionOrBlock() {
		ExpressionOrBlockContext _localctx = new ExpressionOrBlockContext(Context, State);
		EnterRule(_localctx, 20, RULE_expressionOrBlock);
		int _la;
		try {
			int _alt;
			State = 126;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LeftBrace:
				_localctx = new BlockExpressionContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 114;
				Match(LeftBrace);
				State = 118;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 115;
						((BlockExpressionContext)_localctx)._statement = statement();
						((BlockExpressionContext)_localctx)._Statements.Add(((BlockExpressionContext)_localctx)._statement);
						}
						} 
					}
					State = 120;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
				}
				State = 122;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 58880L) != 0)) {
					{
					State = 121;
					((BlockExpressionContext)_localctx).Tail = expression(0);
					}
				}

				State = 124;
				Match(RightBrace);
				}
				break;
			case TrueKeyword:
			case FalseKeyword:
			case String:
			case Integer:
			case Identifier:
				_localctx = new NonBlockExpressionContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 125;
				((NonBlockExpressionContext)_localctx).Expression = expression(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ComparisonExpressionContext : ExpressionContext {
		public ExpressionContext Left;
		public IToken Operator;
		public ExpressionContext Right;
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LessThan() { return GetToken(Ca21Parser.LessThan, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LessThanOrEqual() { return GetToken(Ca21Parser.LessThanOrEqual, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GreaterThan() { return GetToken(Ca21Parser.GreaterThan, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GreaterThanOrEqual() { return GetToken(Ca21Parser.GreaterThanOrEqual, 0); }
		public ComparisonExpressionContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class FactorExpressionContext : ExpressionContext {
		public ExpressionContext Left;
		public IToken Operator;
		public ExpressionContext Right;
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Star() { return GetToken(Ca21Parser.Star, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Slash() { return GetToken(Ca21Parser.Slash, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Percentage() { return GetToken(Ca21Parser.Percentage, 0); }
		public FactorExpressionContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class TermExpressionContext : ExpressionContext {
		public ExpressionContext Left;
		public IToken Operator;
		public ExpressionContext Right;
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Plus() { return GetToken(Ca21Parser.Plus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus() { return GetToken(Ca21Parser.Minus, 0); }
		public TermExpressionContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class AssignmentExpressionContext : ExpressionContext {
		public ExpressionContext Assignee;
		public ExpressionContext Value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Equal() { return GetToken(Ca21Parser.Equal, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public AssignmentExpressionContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class LiteralExpressionContext : ExpressionContext {
		public LiteralContext Literal;
		[System.Diagnostics.DebuggerNonUserCode] public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public LiteralExpressionContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class NameExpressionContext : ExpressionContext {
		public IToken Name;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(Ca21Parser.Identifier, 0); }
		public NameExpressionContext(ExpressionContext context) { CopyFrom(context); }
	}
	public partial class CallExpressionContext : ExpressionContext {
		public ExpressionContext Callee;
		public ArgumentListContext ArgumentList;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParenthesis() { return GetToken(Ca21Parser.LeftParenthesis, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParenthesis() { return GetToken(Ca21Parser.RightParenthesis, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		public CallExpressionContext(ExpressionContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 22;
		EnterRecursionRule(_localctx, 22, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 131;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TrueKeyword:
			case FalseKeyword:
			case String:
			case Integer:
				{
				_localctx = new LiteralExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 129;
				((LiteralExpressionContext)_localctx).Literal = literal();
				}
				break;
			case Identifier:
				{
				_localctx = new NameExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 130;
				((NameExpressionContext)_localctx).Name = Match(Identifier);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 153;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 151;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
					case 1:
						{
						_localctx = new FactorExpressionContext(new ExpressionContext(_parentctx, _parentState));
						((FactorExpressionContext)_localctx).Left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 133;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 134;
						((FactorExpressionContext)_localctx).Operator = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 29360128L) != 0)) ) {
							((FactorExpressionContext)_localctx).Operator = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 135;
						((FactorExpressionContext)_localctx).Right = expression(5);
						}
						break;
					case 2:
						{
						_localctx = new TermExpressionContext(new ExpressionContext(_parentctx, _parentState));
						((TermExpressionContext)_localctx).Left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 136;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 137;
						((TermExpressionContext)_localctx).Operator = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==Plus || _la==Minus) ) {
							((TermExpressionContext)_localctx).Operator = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 138;
						((TermExpressionContext)_localctx).Right = expression(4);
						}
						break;
					case 3:
						{
						_localctx = new ComparisonExpressionContext(new ExpressionContext(_parentctx, _parentState));
						((ComparisonExpressionContext)_localctx).Left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 139;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 140;
						((ComparisonExpressionContext)_localctx).Operator = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 2013265920L) != 0)) ) {
							((ComparisonExpressionContext)_localctx).Operator = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 141;
						((ComparisonExpressionContext)_localctx).Right = expression(3);
						}
						break;
					case 4:
						{
						_localctx = new AssignmentExpressionContext(new ExpressionContext(_parentctx, _parentState));
						((AssignmentExpressionContext)_localctx).Assignee = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 142;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 143;
						Match(Equal);
						State = 144;
						((AssignmentExpressionContext)_localctx).Value = expression(2);
						}
						break;
					case 5:
						{
						_localctx = new CallExpressionContext(new ExpressionContext(_parentctx, _parentState));
						((CallExpressionContext)_localctx).Callee = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 145;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 146;
						Match(LeftParenthesis);
						State = 148;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 58880L) != 0)) {
							{
							State = 147;
							((CallExpressionContext)_localctx).ArgumentList = argumentList();
							}
						}

						State = 150;
						Match(RightParenthesis);
						}
						break;
					}
					} 
				}
				State = 155;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArgumentListContext : ParserRuleContext {
		public ExpressionContext _expression;
		public IList<ExpressionContext> _Arguments = new List<ExpressionContext>();
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(Ca21Parser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(Ca21Parser.Comma, i);
		}
		public ArgumentListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argumentList; } }
	}

	[RuleVersion(0)]
	public ArgumentListContext argumentList() {
		ArgumentListContext _localctx = new ArgumentListContext(Context, State);
		EnterRule(_localctx, 24, RULE_argumentList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156;
			_localctx._expression = expression(0);
			_localctx._Arguments.Add(_localctx._expression);
			State = 161;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 157;
				Match(Comma);
				State = 158;
				_localctx._expression = expression(0);
				_localctx._Arguments.Add(_localctx._expression);
				}
				}
				State = 163;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
	 
		public LiteralContext() { }
		public virtual void CopyFrom(LiteralContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TrueLiteralContext : LiteralContext {
		public IToken Value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TrueKeyword() { return GetToken(Ca21Parser.TrueKeyword, 0); }
		public TrueLiteralContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class StringLiteralContext : LiteralContext {
		public IToken Value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode String() { return GetToken(Ca21Parser.String, 0); }
		public StringLiteralContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class IntegerLiteralContext : LiteralContext {
		public IToken Value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Integer() { return GetToken(Ca21Parser.Integer, 0); }
		public IntegerLiteralContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class FalseLiteralContext : LiteralContext {
		public IToken Value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FalseKeyword() { return GetToken(Ca21Parser.FalseKeyword, 0); }
		public FalseLiteralContext(LiteralContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 26, RULE_literal);
		try {
			State = 168;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Integer:
				_localctx = new IntegerLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 164;
				((IntegerLiteralContext)_localctx).Value = Match(Integer);
				}
				break;
			case TrueKeyword:
				_localctx = new TrueLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 165;
				((TrueLiteralContext)_localctx).Value = Match(TrueKeyword);
				}
				break;
			case FalseKeyword:
				_localctx = new FalseLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 166;
				((FalseLiteralContext)_localctx).Value = Match(FalseKeyword);
				}
				break;
			case String:
				_localctx = new StringLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 167;
				((StringLiteralContext)_localctx).Value = Match(String);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 11: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		case 3: return Precpred(Context, 1);
		case 4: return Precpred(Context, 5);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,32,171,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,1,0,4,0,30,
		8,0,11,0,12,0,31,1,0,1,0,1,1,3,1,37,8,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
		1,1,1,1,1,3,1,49,8,1,1,2,1,2,1,2,1,2,3,2,55,8,2,1,2,1,2,3,2,59,8,2,1,3,
		1,3,1,3,5,3,64,8,3,10,3,12,3,67,9,3,1,4,3,4,70,8,4,1,4,1,4,1,4,1,5,1,5,
		1,6,1,6,1,6,3,6,80,8,6,1,7,1,7,5,7,84,8,7,10,7,12,7,87,9,7,1,7,1,7,1,8,
		1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,3,8,104,8,8,1,9,1,9,3,
		9,108,8,9,1,9,1,9,1,9,1,9,1,9,1,10,1,10,5,10,117,8,10,10,10,12,10,120,
		9,10,1,10,3,10,123,8,10,1,10,1,10,3,10,127,8,10,1,11,1,11,1,11,3,11,132,
		8,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,
		1,11,1,11,3,11,149,8,11,1,11,5,11,152,8,11,10,11,12,11,155,9,11,1,12,1,
		12,1,12,5,12,160,8,12,10,12,12,12,163,9,12,1,13,1,13,1,13,1,13,3,13,169,
		8,13,1,13,0,1,22,14,0,2,4,6,8,10,12,14,16,18,20,22,24,26,0,3,1,0,22,24,
		1,0,25,26,1,0,27,30,185,0,29,1,0,0,0,2,48,1,0,0,0,4,50,1,0,0,0,6,60,1,
		0,0,0,8,69,1,0,0,0,10,74,1,0,0,0,12,79,1,0,0,0,14,81,1,0,0,0,16,103,1,
		0,0,0,18,105,1,0,0,0,20,126,1,0,0,0,22,131,1,0,0,0,24,156,1,0,0,0,26,168,
		1,0,0,0,28,30,3,2,1,0,29,28,1,0,0,0,30,31,1,0,0,0,31,29,1,0,0,0,31,32,
		1,0,0,0,32,33,1,0,0,0,33,34,5,0,0,1,34,1,1,0,0,0,35,37,5,2,0,0,36,35,1,
		0,0,0,36,37,1,0,0,0,37,38,1,0,0,0,38,39,3,4,2,0,39,40,3,14,7,0,40,49,1,
		0,0,0,41,42,5,1,0,0,42,43,5,17,0,0,43,44,5,13,0,0,44,45,5,18,0,0,45,46,
		3,4,2,0,46,47,5,21,0,0,47,49,1,0,0,0,48,36,1,0,0,0,48,41,1,0,0,0,49,3,
		1,0,0,0,50,51,5,3,0,0,51,52,5,15,0,0,52,54,5,17,0,0,53,55,3,6,3,0,54,53,
		1,0,0,0,54,55,1,0,0,0,55,56,1,0,0,0,56,58,5,18,0,0,57,59,3,10,5,0,58,57,
		1,0,0,0,58,59,1,0,0,0,59,5,1,0,0,0,60,65,3,8,4,0,61,62,5,16,0,0,62,64,
		3,8,4,0,63,61,1,0,0,0,64,67,1,0,0,0,65,63,1,0,0,0,65,66,1,0,0,0,66,7,1,
		0,0,0,67,65,1,0,0,0,68,70,5,5,0,0,69,68,1,0,0,0,69,70,1,0,0,0,70,71,1,
		0,0,0,71,72,5,15,0,0,72,73,3,10,5,0,73,9,1,0,0,0,74,75,3,12,6,0,75,11,
		1,0,0,0,76,80,5,6,0,0,77,80,5,8,0,0,78,80,5,7,0,0,79,76,1,0,0,0,79,77,
		1,0,0,0,79,78,1,0,0,0,80,13,1,0,0,0,81,85,5,19,0,0,82,84,3,16,8,0,83,82,
		1,0,0,0,84,87,1,0,0,0,85,83,1,0,0,0,85,86,1,0,0,0,86,88,1,0,0,0,87,85,
		1,0,0,0,88,89,5,20,0,0,89,15,1,0,0,0,90,104,3,18,9,0,91,92,5,11,0,0,92,
		93,3,22,11,0,93,94,3,14,7,0,94,104,1,0,0,0,95,96,5,12,0,0,96,97,3,20,10,
		0,97,98,5,21,0,0,98,104,1,0,0,0,99,104,3,14,7,0,100,101,3,22,11,0,101,
		102,5,21,0,0,102,104,1,0,0,0,103,90,1,0,0,0,103,91,1,0,0,0,103,95,1,0,
		0,0,103,99,1,0,0,0,103,100,1,0,0,0,104,17,1,0,0,0,105,107,5,4,0,0,106,
		108,5,5,0,0,107,106,1,0,0,0,107,108,1,0,0,0,108,109,1,0,0,0,109,110,5,
		15,0,0,110,111,5,31,0,0,111,112,3,20,10,0,112,113,5,21,0,0,113,19,1,0,
		0,0,114,118,5,19,0,0,115,117,3,16,8,0,116,115,1,0,0,0,117,120,1,0,0,0,
		118,116,1,0,0,0,118,119,1,0,0,0,119,122,1,0,0,0,120,118,1,0,0,0,121,123,
		3,22,11,0,122,121,1,0,0,0,122,123,1,0,0,0,123,124,1,0,0,0,124,127,5,20,
		0,0,125,127,3,22,11,0,126,114,1,0,0,0,126,125,1,0,0,0,127,21,1,0,0,0,128,
		129,6,11,-1,0,129,132,3,26,13,0,130,132,5,15,0,0,131,128,1,0,0,0,131,130,
		1,0,0,0,132,153,1,0,0,0,133,134,10,4,0,0,134,135,7,0,0,0,135,152,3,22,
		11,5,136,137,10,3,0,0,137,138,7,1,0,0,138,152,3,22,11,4,139,140,10,2,0,
		0,140,141,7,2,0,0,141,152,3,22,11,3,142,143,10,1,0,0,143,144,5,31,0,0,
		144,152,3,22,11,2,145,146,10,5,0,0,146,148,5,17,0,0,147,149,3,24,12,0,
		148,147,1,0,0,0,148,149,1,0,0,0,149,150,1,0,0,0,150,152,5,18,0,0,151,133,
		1,0,0,0,151,136,1,0,0,0,151,139,1,0,0,0,151,142,1,0,0,0,151,145,1,0,0,
		0,152,155,1,0,0,0,153,151,1,0,0,0,153,154,1,0,0,0,154,23,1,0,0,0,155,153,
		1,0,0,0,156,161,3,22,11,0,157,158,5,16,0,0,158,160,3,22,11,0,159,157,1,
		0,0,0,160,163,1,0,0,0,161,159,1,0,0,0,161,162,1,0,0,0,162,25,1,0,0,0,163,
		161,1,0,0,0,164,169,5,14,0,0,165,169,5,9,0,0,166,169,5,10,0,0,167,169,
		5,13,0,0,168,164,1,0,0,0,168,165,1,0,0,0,168,166,1,0,0,0,168,167,1,0,0,
		0,169,27,1,0,0,0,20,31,36,48,54,58,65,69,79,85,103,107,118,122,126,131,
		148,151,153,161,168
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Ca21.Antlr
